# -*- coding: utf-8 -*-
"""Decision_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ejd6_bdTd_sU-8ta5EeW6oHTYEYMCM1J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.tree import DecisionTreeClassifier as DTC, DecisionTreeRegressor as DTR
# import data Drug
drug = pd.read_csv( '/content/drug200.csv')
drug

#tampilan grafik
sns.pairplot(data=drug, hue='Drug');

drug.info()

drug.describe(include='O')

from sklearn.preprocessing import LabelEncoder

label_enc = LabelEncoder()

cols = drug.select_dtypes(include='O').columns

for col in cols:
    drug[col] = label_enc.fit_transform(drug[col])
# displaying the data after encoding
drug

X = drug.drop(columns='Drug')
y = drug['Drug']
display(X.head(3), y.head(3))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.1, random_state=42)

# Building the model
tree_clf0 = DTC()
# Fitting the model
tree_clf0.fit(X_train,y_train)

tree_clf0.score(X_train, y_train)
tree_clf0.score(X_test, y_test)
from sklearn.metrics import accuracy_score, classification_report
y_pred = tree_clf0.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
accuracy

report = classification_report(y_test, y_pred)
print(report)

from sklearn.tree import plot_tree
plt.figure(figsize=(10, 8), dpi=200)
plot_tree(tree_clf0, feature_names=drug.columns, filled=True);